//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Pose p_player_controller_left_hand;
        
        private static SteamVR_Action_Pose p_player_controller_right_hand;
        
        private static SteamVR_Action_Boolean p_player_controller_grip_right;
        
        private static SteamVR_Action_Boolean p_player_controller_TP_left_press;
        
        private static SteamVR_Action_Boolean p_player_controller_TP_right_press;
        
        private static SteamVR_Action_Vector2 p_player_controller_TP_left_vector;
        
        private static SteamVR_Action_Vector2 p_player_controller_TP_right_vector;
        
        private static SteamVR_Action_Single p_player_controller_trigger_left;
        
        private static SteamVR_Action_Single p_player_controller_trigger_right;
        
        private static SteamVR_Action_Boolean p_player_controller_grip_left;
        
        private static SteamVR_Action_Single p_player_controller_gripForce_left;
        
        private static SteamVR_Action_Single p_player_controller_gripForce_right;
        
        public static SteamVR_Action_Pose player_controller_left_hand
        {
            get
            {
                return SteamVR_Actions.p_player_controller_left_hand.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Pose player_controller_right_hand
        {
            get
            {
                return SteamVR_Actions.p_player_controller_right_hand.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Boolean player_controller_grip_right
        {
            get
            {
                return SteamVR_Actions.p_player_controller_grip_right.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean player_controller_TP_left_press
        {
            get
            {
                return SteamVR_Actions.p_player_controller_TP_left_press.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean player_controller_TP_right_press
        {
            get
            {
                return SteamVR_Actions.p_player_controller_TP_right_press.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 player_controller_TP_left_vector
        {
            get
            {
                return SteamVR_Actions.p_player_controller_TP_left_vector.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Vector2 player_controller_TP_right_vector
        {
            get
            {
                return SteamVR_Actions.p_player_controller_TP_right_vector.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Single player_controller_trigger_left
        {
            get
            {
                return SteamVR_Actions.p_player_controller_trigger_left.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Single player_controller_trigger_right
        {
            get
            {
                return SteamVR_Actions.p_player_controller_trigger_right.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean player_controller_grip_left
        {
            get
            {
                return SteamVR_Actions.p_player_controller_grip_left.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Single player_controller_gripForce_left
        {
            get
            {
                return SteamVR_Actions.p_player_controller_gripForce_left.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Single player_controller_gripForce_right
        {
            get
            {
                return SteamVR_Actions.p_player_controller_gripForce_right.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.player_controller_left_hand,
                    SteamVR_Actions.player_controller_right_hand,
                    SteamVR_Actions.player_controller_grip_right,
                    SteamVR_Actions.player_controller_TP_left_press,
                    SteamVR_Actions.player_controller_TP_right_press,
                    SteamVR_Actions.player_controller_TP_left_vector,
                    SteamVR_Actions.player_controller_TP_right_vector,
                    SteamVR_Actions.player_controller_trigger_left,
                    SteamVR_Actions.player_controller_trigger_right,
                    SteamVR_Actions.player_controller_grip_left,
                    SteamVR_Actions.player_controller_gripForce_left,
                    SteamVR_Actions.player_controller_gripForce_right};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.player_controller_left_hand,
                    SteamVR_Actions.player_controller_right_hand,
                    SteamVR_Actions.player_controller_grip_right,
                    SteamVR_Actions.player_controller_TP_left_press,
                    SteamVR_Actions.player_controller_TP_right_press,
                    SteamVR_Actions.player_controller_TP_left_vector,
                    SteamVR_Actions.player_controller_TP_right_vector,
                    SteamVR_Actions.player_controller_trigger_left,
                    SteamVR_Actions.player_controller_trigger_right,
                    SteamVR_Actions.player_controller_grip_left,
                    SteamVR_Actions.player_controller_gripForce_left,
                    SteamVR_Actions.player_controller_gripForce_right};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[0];
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[0];
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.player_controller_left_hand,
                    SteamVR_Actions.player_controller_right_hand};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.player_controller_grip_right,
                    SteamVR_Actions.player_controller_TP_left_press,
                    SteamVR_Actions.player_controller_TP_right_press,
                    SteamVR_Actions.player_controller_grip_left};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[] {
                    SteamVR_Actions.player_controller_trigger_left,
                    SteamVR_Actions.player_controller_trigger_right,
                    SteamVR_Actions.player_controller_gripForce_left,
                    SteamVR_Actions.player_controller_gripForce_right};
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[] {
                    SteamVR_Actions.player_controller_TP_left_vector,
                    SteamVR_Actions.player_controller_TP_right_vector};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[0];
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.player_controller_grip_right,
                    SteamVR_Actions.player_controller_TP_left_press,
                    SteamVR_Actions.player_controller_TP_right_press,
                    SteamVR_Actions.player_controller_TP_left_vector,
                    SteamVR_Actions.player_controller_TP_right_vector,
                    SteamVR_Actions.player_controller_trigger_left,
                    SteamVR_Actions.player_controller_trigger_right,
                    SteamVR_Actions.player_controller_grip_left,
                    SteamVR_Actions.player_controller_gripForce_left,
                    SteamVR_Actions.player_controller_gripForce_right};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_player_controller_left_hand = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/player_controller/in/left_hand")));
            SteamVR_Actions.p_player_controller_right_hand = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/player_controller/in/right_hand")));
            SteamVR_Actions.p_player_controller_grip_right = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/player_controller/in/grip_right")));
            SteamVR_Actions.p_player_controller_TP_left_press = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/player_controller/in/TP_left_press")));
            SteamVR_Actions.p_player_controller_TP_right_press = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/player_controller/in/TP_right_press")));
            SteamVR_Actions.p_player_controller_TP_left_vector = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/player_controller/in/TP_left_vector")));
            SteamVR_Actions.p_player_controller_TP_right_vector = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/player_controller/in/TP_right_vector")));
            SteamVR_Actions.p_player_controller_trigger_left = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/player_controller/in/trigger_left")));
            SteamVR_Actions.p_player_controller_trigger_right = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/player_controller/in/trigger_right")));
            SteamVR_Actions.p_player_controller_grip_left = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/player_controller/in/grip_left")));
            SteamVR_Actions.p_player_controller_gripForce_left = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/player_controller/in/gripForce_left")));
            SteamVR_Actions.p_player_controller_gripForce_right = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/player_controller/in/gripForce_right")));
        }
    }
}
