//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_player_controller : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Pose left_hand
        {
            get
            {
                return SteamVR_Actions.player_controller_left_hand;
            }
        }
        
        public virtual SteamVR_Action_Pose right_hand
        {
            get
            {
                return SteamVR_Actions.player_controller_right_hand;
            }
        }
    }
}
